- `[x]` **Phase 1: Environment Cleanup**
    - `[x]` Kill zombie Python process (PID 18244)
    - `[x]` Purge stale `temp_audio.wav` files
- `[ ]` **Phase 2: Pipeline Core**
    - `[ ]` Update `Job` class with `enable_lipsync` and `master_ws` flags in `pipeline.py`
    - `[ ]` Implement `translated_segments.json` time-slice inheritance logic
    - `[ ]` Add "Skip Lipsync" branch in `_run_translation_job`
- `[ ]` **Phase 3: MuseTalk Hardening**
    - `[ ]` Verify absolute paths for UNet/VAE in `lipsync_musetalk.py`
    - `[ ]` Fix `sys.executable` propagation and `PYTHONPATH` injection
- `[ ]` **Phase 4: UI Transformation**
    - `[ ]` Implement Timeline Sliders with dynamic duration scaling in `main_ui.py`
    - `[ ]` Add "Enable Lipsync" production toggle
    - `[ ]` Add Master Workspace selection dropdown
- `[ ]` **Phase 5: Launch & Validation**
    - `[ ]` Relaunch via `env\Scripts\python.exe`
    - `[ ]` Test 30s audit of the 86-minute film
