# Code Audit Triage: GeminiCLI vs GLM4 — Cross-Referenced Against Live Code

**Date:** April 12, 2026  
**Audited By:** GeminiCLI (Audit 1) and GLM4 (Audit 2)  
**Triaged By:** Antigravity (this document)

---

## TL;DR — What's Actually Broken Right Now

Both auditors identified real problems, but they were working from **stale log files** and an **older version of the codebase**. Several of their findings have already been fixed in our sessions. However, they both converge on **3 critical issues that are still live and will block the pipeline**.

| # | Issue | Severity | Status | Safe to Fix? |
|---|-------|----------|--------|--------------|
| 1 | **MuseTalk uses `"python"` instead of `sys.executable`** | 🔴 CRITICAL | CONFIRMED LIVE | ✅ Yes |
| 2 | **Missing model assets: `face-parse-bisent`, `sd-vae`** | 🔴 CRITICAL | CONFIRMED LIVE | ✅ Yes |
| 3 | **MuseTalk UNet config path mismatch** | 🔴 CRITICAL | CONFIRMED LIVE | ✅ Yes |
| 4 | **Pipeline doesn't validate stage outputs (silent `None`)** | 🟡 HIGH | CONFIRMED LIVE | ✅ Yes |
| 5 | **Final `ffmpeg` call missing `check=True`** | 🟡 HIGH | CONFIRMED LIVE | ✅ Yes |
| 6 | **`COQUI_TOS_AGREED` not set in `main_ui.py`** | 🟡 HIGH | ✅ ALREADY FIXED | N/A |
| 7 | **PyTorch 2.3.1 vs TTS requiring ≥ 2.4** | 🟠 MEDIUM | NEEDS VERIFICATION | ⚠️ Risky |
| 8 | **`StopIteration` in `get_video_info()` on audio files** | 🔴 (was) | ✅ ALREADY FIXED | N/A |
| 9 | **`HfFolder` / `is_torchcodec_available` import error** | 🔴 (was) | ✅ ALREADY FIXED | N/A |
| 10 | **Whisper `int8` / `float32` compute mode** | 🟡 (was) | ✅ ALREADY FIXED | N/A |
| 11 | **Duplicate `libiomp5md.dll` OpenMP deadlock** | 🔴 (was) | ✅ ALREADY FIXED | N/A |

---

## Detailed Triage Per Finding

### ✅ Already Fixed (No Action Needed)

#### Issue 8: `StopIteration` in `get_video_info()` (GLM4 Primary Finding)
- **GLM4's Claim:** `transcribe.py` calls `get_video_info()` on an audio `.wav` file, causing `StopIteration` because no video stream exists.
- **Current Reality:** The current `transcribe.py` (74 lines) does **NOT** call `get_video_info()` at all. It extracts duration via a direct `ffmpeg -i` stderr parse (lines 17-25). The GLM4 auditor was reading from a **stale traceback log** (`workspace/1775506855/process_trace.log`) that referenced an older version of the code.
- **Verdict:** ✅ **Already fixed in a prior session. No action needed.**

#### Issue 9: `HfFolder` / `is_torchcodec_available` ImportError
- **Both Auditors' Claim:** Gradio crashes on import because newer `huggingface_hub` removed `HfFolder`.
- **Current Reality:** `main_ui.py` lines 13-26 contain the monkey patches that inject `MockHfFolder` and `is_torchcodec_available` before `import gradio`. This was fixed across our earlier sessions.
- **Verdict:** ✅ **Already fixed. No action needed.**

#### Issue 6: Coqui TOS blocking prompt
- **Found during our test run** on Apr 7. `COQUI_TOS_AGREED=1` was injected.
- **Current Reality:** Checking `main_ui.py`... Actually, checking the current file, this env var is **NOT** present in the latest `main_ui.py` (the file was apparently regenerated by one of the other auditors). **This needs to be re-applied.**
- **Verdict:** ⚠️ **Needs re-application — see fix plan below.**

---

### 🔴 CRITICAL — Still Live, Must Fix

#### Issue 1: MuseTalk uses `"python"` instead of `sys.executable`
- **GeminiCLI Finding (2.1):** `lipsync_musetalk.py` line 38 uses `"python"` which finds the wrong interpreter.
- **Verified:** Current code at line 38: `"python", "tools/MuseTalk/scripts/inference.py"` — **CONFIRMED.**
- **Impact:** On Windows with venv, `"python"` resolves to the system Python (3.10/3.11) instead of `env\Scripts\python.exe`, causing immediate `ImportError` on `import torch`.
- **Fix:** Replace `"python"` with `sys.executable`. Zero risk to dependencies.

#### Issue 2: Missing Model Assets (`face-parse-bisent`, `sd-vae`)
- **GeminiCLI Finding (2.2):** MuseTalk requires `face-parse-bisent` and `sd-vae` model directories.
- **Verified:** `face-parse-bisent MISSING`, `sd-vae MISSING` — **CONFIRMED.**
- **Impact:** MuseTalk's `inference.py` will crash or attempt to download models (which fails because `HF_HUB_OFFLINE=1`).
- **Fix:** Download these models from HuggingFace. This requires temporary internet access but won't affect any existing dependencies.

#### Issue 3: MuseTalk UNet Config Path Mismatch
- **GeminiCLI Finding (2.2):** `inference.py` expects `models/musetalk/config.json` but the actual file is at `models/musetalk/musetalk/musetalk.json` (and `musetalkV15/musetalk.json`).
- **Verified:** Confirmed — no `config.json` exists at the expected root path. The actual UNet weights and config are nested one level deeper.
- **Fix:** Pass explicit `--unet_config` and `--unet_model_path` arguments when invoking `inference.py`, or create symlinks. Zero risk to dependencies.

---

### 🟡 HIGH — Still Live, Should Fix

#### Issue 4: Pipeline Doesn't Validate Stage Outputs
- **GeminiCLI Finding (2.3):** `run_lipsync_stage` returns `None` if MuseTalk output is missing, but `pipeline.py` never checks this.
- **Verified:** `pipeline.py` line 194 calls `run_lipsync_stage(vid_25, mix_w, ws, job)` but **discards the return value**. Line 199 then blindly assumes `lipsynced_video.mp4` exists.
- **Impact:** Job status becomes "completed" with a corrupt or missing output file.
- **Fix:** Add return value validation and raise on `None`. Zero risk.

#### Issue 5: Final `ffmpeg` Call Missing `check=True`
- **GeminiCLI Finding (2.3):** `pipeline.py` line 199 uses `subprocess.run(...)` without `check=True`.
- **Verified:** **CONFIRMED.** If the final mux fails (e.g., missing input file), it silently succeeds.
- **Fix:** Add `check=True`. Zero risk.

---

### 🟠 MEDIUM — Valid Concern, But HIGH RISK to Fix Right Now

#### Issue 7: PyTorch 2.3.1 vs TTS ≥ 2.4 Requirement
- **GLM4 Finding:** TTS requires PyTorch ≥ 2.4, current version is 2.3.1+cu121.
- **Current Reality:** TTS version is `0.28.0.dev0` and it imports successfully with our monkey patches. The `is_torch_greater_or_equal` stub in `main_ui.py` line 17 returns `True` unconditionally, which bypasses the version gate.
- **Risk Assessment:** Upgrading PyTorch from 2.3.1 to 2.4+ on this environment would:
  - Require reinstalling `torch`, `torchaudio`, `torchvision` (CUDA-specific wheels)
  - Potentially break `ctranslate2` (faster-whisper backend), `demucs`, `rtmlib`, `onnxruntime-gpu`
  - Risk cascading dependency failures that took us days to stabilize
- **Verdict:** ⚠️ **Do NOT upgrade PyTorch right now.** The monkey patch is working. Revisit only after the pipeline runs end-to-end successfully.

---

## Recommended Implementation Order

### Phase 1: Surgical Strikes (Can do immediately, zero dep risk)

```
1. Fix sys.executable in lipsync_musetalk.py  (Issue 1)
2. Add COQUI_TOS_AGREED=1 to main_ui.py      (Issue 6 re-apply)  
3. Add check=True to final ffmpeg call        (Issue 5)
4. Add return value validation in pipeline.py (Issue 4)
5. Pass explicit model paths to MuseTalk cmd  (Issue 3)
```

### Phase 2: Model Downloads (Requires internet, then back to offline)

```
6. Download face-parse-bisent model           (Issue 2)
7. Download sd-vae model                      (Issue 2)
8. Verify MuseTalk Whisper model format       (Issue 2)
```

### Phase 3: Do NOT Touch (Stable via workarounds)

```
❌ PyTorch upgrade (Issue 7) — monkey patch is sufficient
❌ StopIteration fix (Issue 8) — already resolved in current code
❌ HfFolder patch (Issue 9) — already resolved in current code
```

---

## Auditor Quality Assessment

| Auditor | Accuracy | Depth | Actionability | Staleness Risk |
|---------|----------|-------|---------------|----------------|
| **GeminiCLI** | 🟢 High | Deep — found MuseTalk subprocess + model layout issues | Excellent — specific file/line references | Low — analyzed current source |
| **GLM4** | 🟡 Medium | Broad but surface — good structure, lots of boilerplate | Mixed — many recommendations are generic | High — primary finding based on stale logs |

> [!IMPORTANT]
> **GeminiCLI's findings are more actionable and accurate for our current codebase.** The GLM4 auditor produced a thorough-looking report but its primary diagnosis (StopIteration in transcribe.py) was based on old log files and does not reflect the current code. Its PyTorch upgrade recommendation, if followed blindly, would likely destabilize the entire environment.

---

## Files That Will Be Modified

| File | Changes |
|------|---------|
| [lipsync_musetalk.py](file:///c:/just-dub-it2/app/stages/lipsync_musetalk.py) | `sys.executable`, explicit model paths |
| [pipeline.py](file:///c:/just-dub-it2/app/pipeline.py) | Return validation, `check=True` |
| [main_ui.py](file:///c:/just-dub-it2/app/main_ui.py) | Re-add `COQUI_TOS_AGREED=1` |
