- [x] Setup Tracking
- [x] Modify `main_ui.py`
    - [x] Update `format_time` to `DD:HH:MM:SS`
    - [x] Add `Start point` and `Duration` inputs to UI
    - [x] Add `💾 Preview` link visibility in status table
    - [x] Update `run_mini_test` to become `run_selective_preview`
- [x] Modify `pipeline.py`
    - [x] Implement `preview_dub.mp4` generation logic
    - [x] Implement early exit for `is_preview_selection` jobs
- [x] Verify functionality with a quick test.
